### ISSUE TITLE
Demo sswitch: after executing the script run.sh, h3 cannot ping to h4?

### ISSUE THREAD

**Issue by chenxiang2019** [Emil-501/block.p4#5]
Something unexcept happened.

## Except: 
- h1 cannot ping to h3
- h2 cannot ping to h4

## Now:

```
mininet> pingall
*** Ping: testing ping reachability
h1 -> h2 X h4 
h2 -> h1 h3 X 
h3 -> X h2 X 
h4 -> h1 X h3 
*** Results: 41% dropped (7/12 received)
```

The result showed me that the h3 cannot ping to h4 but h4 can ping to h3... I'm confused about that. Is it something wrong with my commands? But when I executed `h3 ping h4` in the mininet shell, it successfully:

```
mininet> h3 ping h4 -c 3
PING 10.0.0.4 (10.0.0.4) 56(84) bytes of data.
64 bytes from 10.0.0.4: icmp_seq=1 ttl=64 time=0.732 ms
64 bytes from 10.0.0.4: icmp_seq=2 ttl=64 time=0.906 ms
64 bytes from 10.0.0.4: icmp_seq=3 ttl=64 time=1.36 ms

--- 10.0.0.4 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 0.732/0.999/1.360/0.265 ms
```

I think maybe something was wrong with the mininet?

**Comment by peiqiaoWang** [comment]
I feel puzzle when I capture the packet on the four ports of the switch just now....

I sorry. Can you descirbe the function of the switch more detail? For example, which port has what function.. 

thx~

**Comment by peiqiaoWang** [comment]
What reason for that 

> you can capture the icmp packets (h1 to h2 or h2 to h4) on the port 3

**Comment by chenxiang2019** [comment]
@peiqiaoWang 
I mentioned "icmp packets" that means before you starting the capture in port 3, you should execute ping in the mininet shell.

Please notice that, the functions sswitch supported lied in layer 2 to 7. So not the l2 port but the whole switch support them.
